version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_todo_list
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - db-todo-list

networks:
  db-todo-list:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"
